//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGallery.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int WebImageId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Details { get; set; }
        public string Make { get; set; }
        public string Modal { get; set; }
        public string Registration { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
    }
}
